---
- name: Create an EC2 instance
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  become: true
  gather_facts: False
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ name }}"
        region: "us-east-1"
        key_name: ansible
        vpc_subnet_id: vpc-023304be950ab18d8
        instance_type: "{{ size }}"
        security_group: launch-wizard
        network:
          device_index: 0
          assign_public_ip: true
        image_id: ami-00a929b66ed6e0de6
        tags:
          Environment: Testing
      register: ec2

    - name: Print new instance ID
      debug:
        msg: "EC2 instance ID is {{ ec2.instance_ids[0] }}"
