---
- name: Create an EC2 instance
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  gather_facts: False
  tasks:
    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        name: "{{ name }}"
        region: "us-east-1"
        key_name: ansible
        vpc_subnet_id: subnet-011fb62667a064b08
        instance_type: "{{ size }}"
        security_group: sg-0a0c3bfac8698113f
        network:
          assign_public_ip: true
        image_id: ami-00adafae70b8029d8
        tags:
          Environment: Testing
      register: ec2

    - name: Print new instance ID
      debug:
        msg: "EC2 instance ID is {{ ec2.instance_ids[0] }}"
